name: Deployment

on:
  push:
    branches:
      - main

jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: hola
        run: echo ${{ secrets.sex }}
      - uses: actions/checkout@v3
        with:
          token: ${{ github.token }}
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: actions/checkout@v3
      - run: |
          date > generated.txt
          npm install
          npm run build
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "BUILD"
          git push